name: BS$ TOR SCRAPER

on:
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up TOR
        run: |
          sudo apt-get install tor
          echo "ControlPort 9051" | sudo tee -a /etc/tor/torrc
          echo "HashedControlPassword $(tor --hash-password YOUR_TOR_PASSWORD)" | sudo tee -a /etc/tor/torrc
          sudo systemctl restart tor

      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install dependencies
        run: |
          pip install requests[socks] stem beautifulsoup4

      - name: Run TOR Scraper Script
        run: python Groups/laster.py

      - name: Commit and push changes
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git config credential.helper store
          git add .  # Add all changes to the staging area
          git commit -m "Auto-commit by GitHub Actions"
          git push https://GH_PAT@github.com/ASP-Christian/sample-website-ransomwatch.git HEAD:main
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
