name: Update Recent Data

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'  # Use Python 3

    - name: Install dependencies
      run: pip install -r requirements.txt  # If you have any Python dependencies, list them in requirements.txt

    - name: Run recent_selector.py
      run: python Groups/recent_selector.py

    - name: Commit and push changes
      run: |
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"
        git config credential.helper store
        git add Groups/Overall_data/recent_data.json
        git commit -m "Update recent_data.json"
        git push https://GH_PAT@github.com/ASP-Christian/sample-website-ransomwatch.git HEAD:main
      env:
        GH_PAT: ${{ secrets.GH_PAT }}

