name: Run Qilin Blog

on:
  workflow_dispatch:  # Manually trigger the workflow

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    # Note: No need to set up Docker explicitly, as it's available on GitHub-hosted runners

    - name: Build Docker image
      run: docker build -t docker-scrape-runner .

    - name: Run Docker container
      run: docker run --rm docker-scrape-runner
