name: Run Qilin Blog

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x  # Specify the Python version you need

    - name: Install dependencies
      run: pip install -r requirements.txt

    # Install Firefox
    - name: Install Firefox
      run: |
        choco install firefox -y

    # Install Geckodriver for Windows
    - name: Install Geckodriver
      run: |
        $geckodriver_version = "0.33.0"  # Replace with the Geckodriver version you need
        $geckodriver_url = "https://github.com/mozilla/geckodriver/releases/download/v$geckodriver_version/geckodriver-v$geckodriver_version-win64.zip"
        Invoke-WebRequest -Uri $geckodriver_url -OutFile "geckodriver.zip"
        Expand-Archive -Path "geckodriver.zip" -DestinationPath $env:ProgramFiles
        Remove-Item "geckodriver.zip"

    - name: Run scraper
      run: python Qilin_Blog.py  # Replace with the actual filename of your script
