name: Run Python Script

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Docker image
        run: docker build -t my-python-script .

      - name: Run Python script in Docker container
        run: docker run my-python-script

