name: Run Qilin Blog

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x  # Specify the Python version you need

    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        # Download and install Firefox and Geckodriver
        sudo apt-get update
        sudo apt-get install firefox-geckodriver

    - name: Run scraper
      run: python Qilin_Blog.py  # Replace with the actual filename of your script
