name: Run Qilin Blog

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x  # Specify the Python version you need

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Set up Firefox
      uses: actions/setup-firefox@v3  # Use the setup-firefox action
      with:
        headless: true  # You can choose to run Firefox in headless mode or not

    - name: Run scraper
      run: python Qilin_Blog.py  # Replace with the actual filename of your script