name: Run Qilin Blog

on:
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x  # Use the appropriate Python version

    - name: Install dependencies
      run: pip install -r requirements.txt  # Add any required packages to requirements.txt

    - name: Install Tor
      run: sudo apt-get install tor

    - name: Start Tor
      run: sudo service tor start

    - name: Run Python script
      run: python Groups/Qilin_Blog.py

    - name: Stop Tor
      run: sudo service tor stop