name: Run Qilin Blog

on:
  push:
    branches:
      - main  # Adjust this branch name to match your repository's main branch

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      xvfb:
        image: dorowu/ubuntu-desktop-lxde-vnc
        ports:
          - 5900/tcp
        options: --privileged

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build Docker image
      run: docker build -t my-docker-image .

    - name: Run Docker container
      run: docker run --rm --net=host my-docker-image
