name: Run Qilin Blog

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x  # Specify the Python version you need

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Install Firefox
      run: |
        sudo apt-get update
        sudo apt-get install firefox -y

    - name: Use local geckodriver.exe
      run: |
        # Copy the local geckodriver.exe to the appropriate location
        cp geckodriver.exe /usr/local/bin/
        chmod +x /usr/local/bin/geckodriver.exe

    - name: Run scraper
      run: python Groups/Qilin_Blog.py  # Replace with the actual filename of your script
