name: Run Qilin Blog

on:
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x  # Use the desired Python version

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Install Tor and Firefox
      run: |
        sudo apt-get update
        sudo apt-get install -y tor firefox-geckodriver

    - name: Start Tor
      run: sudo systemctl start tor

    - name: Run Python script
      run: python Groups/Qilin_Blog.py

    - name: Stop Tor
      run: sudo systemctl stop tor