name: Run Qilin Blog

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build Docker image
      run: docker build -t docker-scrape-runner .

    - name: Run Docker container
      run: docker run --rm docker-scrape-runner

    - name: Check Git status
      run: git status

    - name: Commit and push changes
      run: |
        git config user.email "github-actions@example.com"
        git config user.name "GitHub Actions"
        git checkout main  # Replace 'main' with the name of your default branch
        git add Overall_data/data_post.json
        git commit -m "Update data_post.json"
        git push
