name: Sample2

on:
  workflow_dispatch:

jobs:
  run_script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install Tor
        run: |
          sudo apt-get update
          sudo apt-get install -y tor
        continue-on-error: true

      - name: Start Tor Service
        run: sudo service tor start

      - name: Wait for Tor Proxy to Start
        run: |
          max_attempts=30
          delay=5
          for i in $(seq 1 $max_attempts); do
            if nc -z 127.0.0.1 9150; then
              echo "Tor proxy is running."
              break
            fi
            if [ $i -eq $max_attempts ]; then
              echo "Failed to start Tor proxy after waiting."
              sudo service tor stop  # Stop Tor if it didn't start correctly
              exit 1
            fi
            sleep $delay
          done

      - name: Set up Python Environment
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
        env:
          TOR_PROXY_HOST: "127.0.0.1"
          TOR_PROXY_PORT: "9150"

      - name: Download and Install geckodriver
        run: |
          LATEST_GECKO_VERSION=$(curl -s https://api.github.com/repos/mozilla/geckodriver/releases/latest | jq -r .tag_name)
          wget "https://github.com/mozilla/geckodriver/releases/download/$LATEST_GECKO_VERSION/geckodriver-$LATEST_GECKO_VERSION-linux64.tar.gz"
          tar -xzf "geckodriver-$LATEST_GECKO_VERSION-linux64.tar.gz"
          chmod +x geckodriver
          sudo mv geckodriver /usr/local/bin/
          rm "geckodriver-$LATEST_GECKO_VERSION-linux64.tar.gz"

      - name: Wait for Xvfb to start (workaround for headless Firefox)
        run: sleep 5

      - name: Run Qilin Blog Script
        run: python Groups/sample2.py

      - name: Stop Tor Service
        run: sudo service tor stop
