name: Sample2

on:
  workflow_dispatch:

jobs:
  run_script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install Tor
        run: |
          sudo apt-get update
          sudo apt-get install -y tor
        continue-on-error: true

      - name: Start Tor Service
        run: sudo service tor start

      - name: Set up Python Environment
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
        env:
          TOR_PROXY_HOST: "127.0.0.1"
          TOR_PROXY_PORT: "9150"

      - name: Run Qilin Blog Script
        run: python Groups/sample2.py

      - name: Stop Tor Service
        run: sudo service tor stop
