name: Create Directory and JSON

on:
  push:
    branches:
      - main

jobs:
  create_directory_and_json:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x

    - name: Create Directory and JSON
      run: python ./create_directory_and_json.py

    - name: Commit and Push Changes
      run: |
        git config --global user.name "Your Name"
        git config --global user.email "youremail@example.com"
        git add my_new_directory
        git commit -m "Add new directory and JSON file"
        git push
