name: Run Qilin Blog

on:
  workflow_dispatch:  # Manually trigger the workflow

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker
      uses: docker/setup-docker@v2

    - name: Build Docker image
      run: docker build -t qilin-blog .

    - name: Run Docker container
      run: docker run --rm qilin-blog
