name: Run Qilin Blog

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x  # Specify the Python version you need

    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        # Download and install the Firefox WebDriver for Windows using curl
          curl -Lo geckodriver.zip https://github.com/mozilla/geckodriver/releases/download/v0.30.0/geckodriver-v0.30.0-win64.zip
          Expand-Archive -Path geckodriver.zip -DestinationPath $env:ProgramFiles\geckodriver
          Remove-Item geckodriver.zip

    - name: Run scraper
      run: python Groups/Qilin_Blog.py  # Replace with the actual filename of your script
