name: Scrape Tor Website

on:
  push:
    branches:
      - main

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Tor
      run: |
        sudo apt-get install tor
        sudo service tor start

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x

    - name: Install dependencies
      run: |
        pip install requests[socks]
        pip install beautifulsoup4

    - name: Run Python script
      run: |
        import requests
        from bs4 import BeautifulSoup
        import socks  # You need to import the 'socks' library
        import socket

        # Configure the SOCKS proxy (Tor)
        socks.set_default_proxy(socks.SOCKS5, "localhost", 9050)  # Assumes Tor is running on the default port
        socket.socket = socks.socksocket  # Configure socket to use the Tor proxy

        # Define the URL of the .onion website you want to scrape
        url = "http://3f7nxkjway3d223j27lyad7v5cgmyaifesycvmwq7i7cbs23lb6llryd.onion"

        # Send an HTTP GET request to the URL
        response = requests.get(url)

        # Get the status code
        status_code = response.status_code

        # Parse the HTML content of the page
        soup = BeautifulSoup(response.content, "html.parser")

        # Find and extract the website title
        title = soup.title.string if soup.title else "Title not found"

        # Print the status code and website title
        print(f"Status Code: {status_code}")
        print(f"Website Title: {title}")
