name: Selenium Scraping with Tor

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install dependencies
        run: |
          pip install selenium
          pip install pyvirtualdisplay

      - name: Start virtual display
        run: |
          export DISPLAY=:99
          Xvfb $DISPLAY -ac &
          sleep 5

      - name: Download Tor Browser
        run: |
          wget https://www.torproject.org/dist/torbrowser/12.5.3/tor-browser-linux64-12.5.3_ALL.tar.xz
          tar -xvf tor-browser-linux64-12.5.3_ALL.tar.xz
          # Adjust the directory name as needed based on the actual structure
          cd tor-browser-linux64-12.5.3_ALL/
          ./start-tor-browser.desktop &
        shell: /usr/bin/bash -e {0}


      - name: Run Selenium Script
        run: |
          python your_selenium_script.py

      - name: Stop Tor Browser
        run: |
          pkill -f start-tor-browser.desktop

      - name: Stop virtual display
        run: |
          pkill Xvfb
