name: Selenium Web Scraping

on:
  push:
    branches:
      - main  # Replace with the branch you want to trigger the action on

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8  # You can change this to your preferred Python version

      - name: Install dependencies
        run: |
          pip install selenium
          # You may need to install geckodriver if it's not available on the runner
          # Example command for Ubuntu:
          # sudo apt-get install firefox-geckodriver

      - name: Run Python script
        run: |
          python Groups/sample.py
        continue-on-error: true  # Continue execution even if there's an error