name: Run Python Script with Selenium and Tor

on: [push]

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x  # Replace with your desired Python version

    - name: Install dependencies
      run: |
        pip install selenium
        # Install Tor if not already available (you may need to adjust this based on your setup)
        sudo apt-get update
        sudo apt-get install -y tor

    - name: Start Tor service
      run: |
        sudo service tor start
        # Check if Tor is running
        sudo service tor status

    - name: Check Tor configuration
      run: |
        # Check Tor's configuration
        cat /etc/tor/torrc

    - name: Download and install GeckoDriver
      run: |
        wget https://github.com/mozilla/geckodriver/releases/download/v0.33.0/geckodriver-v0.33.0-linux64.tar.gz
        tar -xvf geckodriver-v0.33.0-linux64.tar.gz
        chmod +x geckodriver
        sudo mv geckodriver /usr/local/bin/
        # Verify GeckoDriver installation
        which geckodriver

    - name: Run Python script
      run: |
        python Groups/sample.py
      continue-on-error: true  # Continue execution even if there's an error

    - name: Stop Tor service
      run: |
        sudo service tor stop
        # Check if Tor is stopped
        sudo service tor status || true  # Use '|| true' to avoid workflow failure if Tor is not running

    - name: Check Workflow Status
      run: |
        # Check the exit status of the previous Python script execution
        if [ $? -eq 0 ]; then
          echo "Python script executed successfully."
        else
          echo "Python script failed. Check the logs for details."
        fi
