name: Scrape Onion Site Title

on:
  push:
    branches:
      - main

jobs:
  scrape_onion_title:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x

    - name: Install dependencies
      run: |
        pip install selenium
        pip install stem

    - name: Start TOR service
      run: |
        sudo apt-get install tor
        sudo service tor start
        sleep 5 # Wait for TOR to start

    - name: Run Python script
      run: |
        python Groups/sample.py
