name: Run Python Script with Selenium and Tor

on: [push]

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x  # Replace with your desired Python version

    - name: Install dependencies
      run: |
        pip install selenium
        # Install Tor if not already available (you may need to adjust this based on your setup)
        sudo apt-get update
        sudo apt-get install -y tor

    - name: Start Tor service
      run: sudo service tor start

    - name: Check Tor status and configuration
      run: |
        # Check if Tor is running
        sudo service tor status

        # Check Tor's configuration
        cat /etc/tor/torrc

    - name: Download and install GeckoDriver
      run: |
        wget https://github.com/mozilla/geckodriver/releases/download/v0.30.0/geckodriver-v0.30.0-linux64.tar.gz
        tar -xvf geckodriver-v0.30.0-linux64.tar.gz
        chmod +x geckodriver
        sudo mv geckodriver /usr/local/bin/

    - name: Run Python script
      run: |
        python Groups/sample.py

    - name: Stop Tor service
      run: sudo service tor stop

