name: Selenium Web Scraping with Tor

on:
  workflow_dispatch:

jobs:
  selenium:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Install Tor
        run: |
          sudo apt-get update
          sudo apt-get install tor

      - name: Configure Tor
        run: |
          echo "SocksPort 9050" | sudo tee -a /etc/tor/torrc
          echo "SocksListenAddress 127.0.0.1" | sudo tee -a /etc/tor/torrc
          echo "SocksPort 9050 IPv6Traffic PreferIPv6 KeepAliveIsolateSOCKSAuth IsolateClientAddr IsolateSOCKSAuth" | sudo tee -a /etc/tor/torrc
          echo "ControlPort 9051" | sudo tee -a /etc/tor/torrc
          echo "CookieAuthentication 1" | sudo tee -a /etc/tor/torrc
          sudo systemctl restart tor

      - name: Install Selenium and geckodriver
        run: |
          pip install selenium
          wget https://github.com/mozilla/geckodriver/releases/download/v0.33.0/geckodriver-v0.33.0-linux64.tar.gz
          tar -xvzf geckodriver-v0.33.0-linux64.tar.gz
          sudo mv geckodriver /usr/local/bin/

      - name: Test Tor Connection
        run: |
          curl --socks5 127.0.0.1:9050 -I https://check.torproject.org

      - name: Run Selenium Script
        run: |
          python your_selenium_script.py  # Replace with the actual name of your Python script

      - name: Stop Tor Service
        run: |
          sudo systemctl stop tor
