name: Run Python script with Firefox and Tor Browser

on:
  push:
    branches:
      - main  # Change this to your main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x  # Choose your desired Python version

    - name: Install dependencies
      run: |
        pip install -r requirements.txt  # Replace with your requirements file if needed

    - name: Download and extract Tor Browser
      run: |
        wget https://www.torproject.org/dist/torbrowser/10.0.0/tor-browser-linux64-10.0.0_en-US.tar.xz
        tar -xvf tor-browser-linux64-10.0.0_en-US.tar.xz

    - name: Set up geckodriver
      run: |
        wget https://github.com/mozilla/geckodriver/releases/download/v0.30.0/geckodriver-v0.30.0-linux64.tar.gz
        tar -xvf geckodriver-v0.30.0-linux64.tar.gz

    - name: Run Python script
      run: python Groups/sample.py  # Replace with the actual name of your Python script


    - name: Cleanup
      run: |
        rm -rf tor-browser-linux64-10.0.0_en-US
        rm geckodriver-v0.30.0-linux64.tar.gz

