name: Run Selenium Script HEEEEEEEEEEEEEEEEEERE

on: [push]


jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up QEMU for cross-platform builds
      uses: docker/setup-qemu-action@v1

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        push: false  # Set this to true if you want to push the image to a Docker registry

    - name: Run Python script inside Docker container
      run: |
        docker run -e TZ=America/New_York my-python-app python sample.py
      env:
        TZ: America/New_York
