name: Run Qilin Blog

on:
  workflow_dispatch:  # Manually trigger the workflow

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Docker image
        run: docker build -t qilin-blog .

      - name: Run Qilin Blog with TOR
        run: docker run --rm -d -p 9150:9150 qilin-blog

      - name: Wait for the service to start
        run: sleep 10

      - name: Run Qilin_Blog.py
        run: docker exec -it $(docker ps -q) python Groups/Qilin_Blog.py
