name: Run Qilin Blog Manually

on:
  workflow_dispatch:  # This event allows manual triggering

jobs:
  run_qilin_blog:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x  # Choose the appropriate Python version

    - name: Install Dependencies
      run: |
        pip install -r requirements.txt

    - name: Start TOR
      run: |
        # Start TOR here (commands to start TOR as a background service)
        # Example: tor &
        
    - name: Run Qilin Blog Script
      run: python Groups/Qilin_Blog.py
