name: Run Qilin Blog Script

on:
  push:
    branches:
      - main  # or the branch you want to trigger the workflow on

jobs:
  run_script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Set up Docker
      uses: docker/setup-docker@v2
      
    - name: Build Docker image
      run: docker build -t qilin-blog .
      
    - name: Run Docker container
      run: docker run -v $PWD/Groups:/app/Groups --network host qilin-blog python3 /app/Qilin_Blog.py
