name: Visit Onion Site

on:
  push:
    branches:
      - main

jobs:
  visit_onion_site:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install selenium stem
          # Download and install the latest TOR browser (update the URL)
          wget https://www.torproject.org/dist/torbrowser/<version>/tor-browser-<platform>-<version>_en-US.tar.xz
          tar -xvf tor-browser-<platform>-<version>_en-US.tar.xz
          mv tor-browser_en-US/ tor-browser/
        working-directory: ${{ github.workspace }}

      - name: Run Python script
        run: |
          python visit_onion_site.py
        env:
          TOR_BROWSER_PATH: './tor-browser'
